pub use diesel_ease_macros::*;

/// The trait for `diesel_ease` macro docs
///
/// This trait is used to generate the docs for the `diesel_ease` macro.
///
/// This trait has all the functions that are generated by the `diesel_ease` macro.
///
/// There are no way to make docs for that functions who will generate by the macro. So this trait is used to generate the documentation.
///     
/// You shouldn't use this trait anywhere. Just use the `diesel_ease` macro.
pub trait MacroDocsTrait {}
